Adding Ansible

diff --git a/.github/workflows/pr_checks.yaml b/.github/workflows/pr_checks.yaml
--- a/.github/workflows/pr_checks.yaml
+++ b/.github/workflows/pr_checks.yaml
@@ -15,3 +15,19 @@ jobs:
         run: |
           echo "Running checks for Pull Request"
           echo "PR: ${{ github.event.pull_request.number }}"
+      
+      - name: Check and Install Ansible
+        run: |
+          if ! command -v ansible &> /dev/null
+          then
+              echo "Ansible not found. Installing Ansible..."
+              sudo apt update
+              sudo apt install -y ansible
+          else
+              echo "Ansible is already installed"
+          fi
+
+      - name: Run Ansible Lint
+        run: |
+          echo "Running Ansible Lint"
+          ansible-lint
